log_destination = 'stderr'
log_line_prefix = '%t [%p]: user=%u,db=%d '
log_statement = 'ddl'
log_min_duration_statement = 200
log_connections = on
log_disconnections = on
log_lock_waits = on
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = 'all'
pg_stat_statements.max = 10000
