[pytest]
asyncio_mode = auto
env =
    POSTGRES_HOST=localhost
    POSTGRES_PORT=5433
    POSTGRES_USER=test_user
    POSTGRES_PASSWORD=test_password
    POSTGRES_DB=depfund_test
    SECRET_KEY=any-secret-for-testing
    LOG_SQL_QUERIES=0
    ADMIN_SECRET_KEY=develop