"""add suffix to project

Revision ID: 493c05d6ee58
Revises: 66b7db660c6c
Create Date: 2026-06-04 08:47:09.391941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493c05d6ee58'
down_revision: Union[str, Sequence[str], None] = '66b7db660c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PROJECT', sa.Column('suffix', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PROJECT', 'suffix')
    # ### end Alembic commands ###
