"""rename_annual_profits_to_annual_gross_profit

Revision ID: ec4a7326d0f2
Revises: 493c05d6ee58
Create Date: 2026-06-04 13:45:18.511931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec4a7326d0f2'
down_revision: Union[str, Sequence[str], None] = '493c05d6ee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PROJECT', sa.Column('annual_gross_profit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('PROJECT', 'annual_profits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PROJECT', sa.Column('annual_profits', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('PROJECT', 'annual_gross_profit')
    # ### end Alembic commands ###
