"""make project fields required

Revision ID: 71727b594df0
Revises: ec4a7326d0f2
Create Date: 2026-06-09 18:10:19.785336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71727b594df0"
down_revision: Union[str, Sequence[str], None] = "ec4a7326d0f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "PROJECT",
        "min_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    op.alter_column(
        "PROJECT",
        "annual_expenses",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    op.alter_column(
        "PROJECT",
        "annual_gross_profit",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=False,
    )
    op.alter_column(
        "PROJECT", "suffix", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "PROJECT", "ubication", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "PROJECT", "ubication", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "PROJECT", "suffix", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "PROJECT",
        "annual_gross_profit",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    op.alter_column(
        "PROJECT",
        "annual_expenses",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    op.alter_column(
        "PROJECT",
        "min_amount",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###
