"""create investment table

Revision ID: 615808ece96b
Revises: e27183c4a1c5
Create Date: 2026-06-26 18:58:18.300400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615808ece96b'
down_revision: Union[str, Sequence[str], None] = 'e27183c4a1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVESTMENT',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['PROJECT.id'], name=op.f('fk_INVESTMENT_project_id_PROJECT')),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], name=op.f('fk_INVESTMENT_user_id_USER')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_INVESTMENT'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVESTMENT')
    # ### end Alembic commands ###
