"""add created_at and updated_at to transaction

Revision ID: 36abc6542739
Revises: 2388c1fdae77
Create Date: 2026-06-27 01:04:53.117754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36abc6542739"
down_revision: Union[str, Sequence[str], None] = "2388c1fdae77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "TRANSACTION",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "TRANSACTION",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("TRANSACTION", "updated_at")
    op.drop_column("TRANSACTION", "created_at")
    # ### end Alembic commands ###
