apiVersion: v1
kind: ConfigMap
metadata:
  name: depfund-config
  namespace: depfund
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SENDER_EMAIL: "depfund.soporte@gmail.com"
  FRONTEND_URL: "https://depfund.34.58.61.129.sslip.io"
  BACKOFFICE_URL: "https://depfund.34.58.61.129.sslip.io/admin"
  TREASURY_ADDRESS: "0x2560d5b0CDe93D618425FadfC9F5511e8730Af90"
  USDC_ADDRESS: "0x35ec429d8a88Dc666921AB7fE97e379Cd980F84E"
  MARKETPLACE_ADDRESS: "0x2292E004e119b4Ec83bc689479EB9bF475AaFa0B"
  FACTORY_ADDRESS: "0x72a804e91730D12221d99f6FB907682c932893a4"
  PLATFORM_ADDRESS: "0x2560d5b0CDe93D618425FadfC9F5511e8730Af90"
  LOG_SQL_QUERIES: "0"
  GOOGLE_REDIRECT_URI: "https://depfund.34.58.61.129.sslip.io/api/auth/google/callback"
  GOOGLE_AUTH_URL: "https://accounts.google.com/o/oauth2/v2/auth"
  GOOGLE_TOKEN_URL: "https://accounts.google.com/o/oauth2/token"
  GOOGLE_USERINFO_URL: "https://www.googleapis.com/oauth2/v3/userinfo"
  BACKUP_NOTIFY_EMAIL: "depfund.soporte@gmail.com"
  DOMAIN: "depfund.34.58.61.129.sslip.io"

  postgresql.conf: |
    log_destination = 'stderr'
    log_line_prefix = '%t [%p]: user=%u,db=%d '
    log_statement = 'ddl'
    log_min_duration_statement = 200
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.track = 'all'
    pg_stat_statements.max = 10000

  init-pg-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
