apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: depfund-secrets
  namespace: depfund
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: depfund-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: depfund-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: depfund-postgres-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: depfund-postgres-db
    - secretKey: SECRET_KEY
      remoteRef:
        key: depfund-secret-key
    - secretKey: ADMIN_SECRET_KEY
      remoteRef:
        key: depfund-admin-secret-key
    - secretKey: SENDER_PASSWORD
      remoteRef:
        key: depfund-sender-password
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: depfund-google-client-id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: depfund-google-client-secret
    - secretKey: GOOGLE_REDIRECT_URI
      remoteRef:
        key: depfund-google-redirect-uri
    - secretKey: CLOUDINARY_CLOUD_NAME
      remoteRef:
        key: depfund-cloudinary-cloud-name
    - secretKey: CLOUDINARY_API_KEY
      remoteRef:
        key: depfund-cloudinary-api-key
    - secretKey: CLOUDINARY_API_SECRET
      remoteRef:
        key: depfund-cloudinary-api-secret
    - secretKey: RPC_URL
      remoteRef:
        key: depfund-rpc-url
    - secretKey: DEPLOYER_PRIVATE_KEY
      remoteRef:
        key: depfund-deployer-private-key
