apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depfund-ingress
  namespace: depfund
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - depfund.34.58.61.129.sslip.io
      secretName: depfund-tls
  rules:
    - host: depfund.34.58.61.129.sslip.io
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: depfund-backoffice
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: depfund-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: depfund-frontend
                port:
                  number: 80
